//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_staff_move
    {
        public int id { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string lantikan_pdf { get; set; }
        public string kenaikan_pdf { get; set; }
        public string pertukaran_pdf { get; set; }
        public string meninggalkan_pdf { get; set; }
        public System.DateTime created_dt { get; set; }
        public string created_by { get; set; }
        public System.DateTime updated_dt { get; set; }
        public string updated_by { get; set; }
    }
}
