//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KTMBEntities : DbContext
    {
        public KTMBEntities()
            : base("name=KTMBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ost_album_list> ost_album_list { get; set; }
        public virtual DbSet<ost_announce> ost_announce { get; set; }
        public virtual DbSet<ost_application> ost_application { get; set; }
        public virtual DbSet<ost_arahan> ost_arahan { get; set; }
        public virtual DbSet<ost_arahan2> ost_arahan2 { get; set; }
        public virtual DbSet<ost_articles> ost_articles { get; set; }
        public virtual DbSet<ost_articles_malam> ost_articles_malam { get; set; }
        public virtual DbSet<ost_audit_trail> ost_audit_trail { get; set; }
        public virtual DbSet<ost_board> ost_board { get; set; }
        public virtual DbSet<ost_board_director> ost_board_director { get; set; }
        public virtual DbSet<ost_board_list> ost_board_list { get; set; }
        public virtual DbSet<ost_bulletin_intranet> ost_bulletin_intranet { get; set; }
        public virtual DbSet<ost_calendar> ost_calendar { get; set; }
        public virtual DbSet<ost_calendar_event> ost_calendar_event { get; set; }
        public virtual DbSet<ost_feedback> ost_feedback { get; set; }
        public virtual DbSet<ost_media> ost_media { get; set; }
        public virtual DbSet<ost_menu> ost_menu { get; set; }
        public virtual DbSet<ost_menu_access> ost_menu_access { get; set; }
        public virtual DbSet<ost_misc> ost_misc { get; set; }
        public virtual DbSet<ost_photo_album> ost_photo_album { get; set; }
        public virtual DbSet<ost_photo_list> ost_photo_list { get; set; }
        public virtual DbSet<ost_poll_answer> ost_poll_answer { get; set; }
        public virtual DbSet<ost_poll_answeredby> ost_poll_answeredby { get; set; }
        public virtual DbSet<ost_poll_question> ost_poll_question { get; set; }
        public virtual DbSet<ost_portal_album> ost_portal_album { get; set; }
        public virtual DbSet<ost_portal_media> ost_portal_media { get; set; }
        public virtual DbSet<ost_ref_cat> ost_ref_cat { get; set; }
        public virtual DbSet<ost_ref_list> ost_ref_list { get; set; }
        public virtual DbSet<ost_report> ost_report { get; set; }
        public virtual DbSet<ost_staff_move> ost_staff_move { get; set; }
        public virtual DbSet<ost_statistic_graph> ost_statistic_graph { get; set; }
        public virtual DbSet<ost_train_schedule> ost_train_schedule { get; set; }
        public virtual DbSet<ost_user> ost_user { get; set; }
        public virtual DbSet<ost_user_group> ost_user_group { get; set; }
        public virtual DbSet<ost_user_online> ost_user_online { get; set; }
        public virtual DbSet<ost_user_poll> ost_user_poll { get; set; }
        public virtual DbSet<ost_user_poll2> ost_user_poll2 { get; set; }
        public virtual DbSet<ost_visitor> ost_visitor { get; set; }
        public virtual DbSet<ost_vote_answer> ost_vote_answer { get; set; }
        public virtual DbSet<ost_vote_answeredby> ost_vote_answeredby { get; set; }
        public virtual DbSet<ost_vote_question> ost_vote_question { get; set; }
    }
}
