//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_application
    {
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string group_app { get; set; }
        public string img_url { get; set; }
        public int sort { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dt { get; set; }
        public string updated_by { get; set; }
        public Nullable<long> sort2 { get; set; }
    }
}
