//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_feedback
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string message { get; set; }
        public System.DateTime dt_send { get; set; }
        public int status { get; set; }
    }
}
