//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_menu
    {
        public int id { get; set; }
        public string title_my { get; set; }
        public string title_en { get; set; }
        public string type { get; set; }
        public int parent_id { get; set; }
        public int sort { get; set; }
        public int display_status { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dt { get; set; }
        public string updated_by { get; set; }
    }
}
