//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_audit_trail
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public int menu_id { get; set; }
        public Nullable<System.DateTime> action_datetime { get; set; }
        public string action_type { get; set; }
        public int data_id { get; set; }
    }
}
