//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_media
    {
        public int id { get; set; }
        public string title_my { get; set; }
        public string img_my { get; set; }
        public string url { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime created_dt { get; set; }
        public string created_by { get; set; }
        public System.DateTime updated_dt { get; set; }
        public string updated_by { get; set; }
    }
}
