//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_articles
    {
        public int id { get; set; }
        public string menu_type { get; set; }
        public int menu_id { get; set; }
        public string title_en { get; set; }
        public string type { get; set; }
        public string url { get; set; }
        public string url_en { get; set; }
        public string content_my { get; set; }
        public string content_en { get; set; }
        public int publish_status { get; set; }
        public string tag { get; set; }
        public int hits { get; set; }
        public string title_my { get; set; }
        public Nullable<System.DateTime> doc_date { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string created_by { get; set; }
        public string created_role { get; set; }
        public string updated_role { get; set; }
        public Nullable<System.DateTime> updated_dt { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> start_dt { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
    }
}
