//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_poll_answeredby
    {
        public int id { get; set; }
        public int question_id { get; set; }
        public int answer_id { get; set; }
        public System.DateTime answer_datetime { get; set; }
        public string answer_by { get; set; }
    }
}
