//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_arahan
    {
        public int id { get; set; }
        public string ref_no { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> upload_dt { get; set; }
        public Nullable<System.DateTime> start_dt { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public string notes { get; set; }
        public string cat { get; set; }
        public string type { get; set; }
        public string doc_url { get; set; }
        public string article { get; set; }
        public int approval_status { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dt { get; set; }
        public string updated_by { get; set; }
    }
}
