//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMB.eTicketing.UI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_user
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public int status { get; set; }
        public string type { get; set; }
        public string role { get; set; }
        public string location { get; set; }
        public System.DateTime date_change_password { get; set; }
        public int block_password { get; set; }
        public Nullable<int> block_trial3 { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dt { get; set; }
        public string updated_by { get; set; }
    }
}
